pkg/sip/service_test.go
Start writing tests that exercise SIP server
=> Add TestService_AuthFailure

pkg/errors/errors.go, pkg/sip/service_test.go
Copied from other ingress/egress
=> Remove unused functions

pkg/sip/inbound.go, pkg/sip/signaling.go
This helps if source is silent or blocked by firewall.
=> Set media destination from SDP.

go.mod, pkg/sip/room.go
Since SIP does not deal with audio, it's better to not initiate subscriptions for them in the first place.
=> Use selective subscriptions and only subscribe to audio tracks

pkg/sip/inbound.go
After this change is live I'll add a follow-up to measure RTP delay. Maybe we could indeed rely on the first packet received as a signal that audio will be accepted without a cutoff.
=> Delay bridging audio for a brief moment to prevent cutoff.

pkg/stats/monitor.go
Up to this point we ere missing the call errors metric. Call termination metric was correct though.
=> Make sure all metrics are registered

pkg/siptest/client.go, test/client/main.go
Add OnBye handler to pkg/siptest.Client
=> Make test/client BYE aware

pkg/sip/outbound.go
=> Remove error from CloseWithReason

pkg/sip/outbound.go
Just to match inbound behavior
=> Call SetDestAddr for outbound calls

go.mod, go.sum, pkg/media/rtp/mux.go, pkg/sip/inbound.go, pkg/sip/media.go, pkg/sip/outbound.go
Implement RTP payload type mux in preparation for adding more audio formats.
=> Implement RTP mux

.github/workflows/build.yaml, .github/workflows/docker.yaml, .github/workflows/test.yaml, cmd/livekit-sip/main.go, go.mod, go.sum, pkg/config/config.go, pkg/service/service.go, pkg/sip/client.go, pkg/sip/config.go, pkg/sip/inbound.go, pkg/sip/outbound.go, pkg/sip/room.go, pkg/sip/server.go, pkg/sip/service.go, pkg/sip/service_test.go, test/integration/sip_test.go, test/lktest/livekit.go, test/lktest/sip.go
Requires https://github.com/livekit/protocol/pull/696 and https://github.com/livekit/livekit/pull/2683
=> Pass new SIP metadata and improve logging.

pkg/sip/signaling.go
Fix SDP codec selection. Fixes #95.
=> Fix SDP codec selection

pkg/config/config.go, pkg/sip/inbound.go, pkg/sip/service_test.go
Send proper call status codes if signalling port is not hidden.
=> Send proper call status codes

pkg/sip/inbound.go, pkg/sip/outbound.go
Improve logging for media and closed calls.
=> Improve logging

pkg/sip/room.go
there's a bit of a race here: as the room is closing and a new track is received we can panic, so check to make sure the room is in a ready state before continuing.
longer term fix will be to add more locking around some of these critical sections; but will let @dennwc fix that when he returns.
=> fix panic when room is closing and new track is received

pkg/service/service.go
Wait for existing calls to complete before shutting down when receiving SIGTERM or SIGQUIT.
Forceful/immediate shutdown will still happen with SIGINT.
=> allow calls to complete during a graceful shutdown

pkg/service/service.go
* allow calls to complete during a graceful shutdown
* graceful shutdown and watch for term signal
=> cherry pick graceful shutdowns to hotfix branch

pkg/media/codecs.go, pkg/media/dtmf/dtmf.go, pkg/media/g711/alaw.go, pkg/media/g711/ulaw.go, pkg/media/g722/g722.go, pkg/media/media.go, pkg/media/opus/opus.go, pkg/media/pcm.go, pkg/media/pipe.go, pkg/media/resample.go, pkg/media/resample_soxr.go, pkg/media/rtp/conn.go, pkg/media/rtp/rtp.go, pkg/media/webm/writer.go, pkg/mixer/mixer.go, pkg/mixer/mixer_test.go, pkg/sip/client.go, pkg/sip/inbound.go, pkg/sip/media_port.go, pkg/sip/media_port_test.go, pkg/sip/outbound.go, pkg/sip/room.go, pkg/sip/signaling.go, pkg/sip/signaling_test.go
Refactor and isolate media pipeline. It is now shared between inbound and outbound. Added tests for media pipeline each supported codec.
=> Refactor and isolate media pipeline

test/lktest/livekit.go
This reverts commit 1266354ea066e80c32dd214f5734570e075cae39.
=> Revert "Set the expected room name in ListRooms requests in the integration test (#214)"

pkg/sip/outbound.go
Annotate auth challenge parsing error to debug #238.
=> Print auth challenge when parsing fails.

pkg/stats/monitor.go
prom does not get initialized until later
=> Actually fix monitor panic

pkg/config/config.go, pkg/sip/config.go, pkg/sip/inbound.go, pkg/sip/outbound.go, pkg/sip/service.go
also reduce annoying ringings every second
=> make media and signaling possible use different ips

pkg/sip/outbound.go
- Fixes twilio typo to get proper error message during auth loop
=> fix(outbound) read error message from twilio auth header

go.mod, go.sum, pkg/sip/inbound.go, pkg/sip/server.go
This will help us detect issues with the singling earlier.
=> Log invite retry attempts.
