- pkg/sip/client.go
- pkg/sip/outbound.go
- pkg/sip/server.go
- pkg/sip/service.go
* Outbound was sharing a port with server. BYE requests would be routed into the server handler. We no longer share the UserAgent so Outbound+Inbound is happening on distinct ports
* Add `Bye` handler to Outbound handler
* Properly build the outbound INVITE request. From header didn't include the CallerID
* Properly build the outbound Ack. Was missing Record-Route
> Implement outbound call hangups

- pkg/config/config.go
- pkg/sip/client.go
- pkg/sip/config.go
- pkg/sip/inbound.go
- pkg/sip/outbound.go
- pkg/sip/server.go
- pkg/sip/service.go
Revert UA change. We must share the UA to keep a single SIP signaling port (and thus the forwarding setup)
Pass unhandled BYE from server to client, so that the outbound call can properly terminate.
Also, allow specifying which local interface to use in the config.
> Revert UA change. Pass BYE from server to client.

- pkg/media/dtmf/dtmf.go
- pkg/media/dtmf/dtmf_test.go
- pkg/media/rtp/codecs.go
- pkg/media/rtp/media.go
- pkg/media/rtp/rtp.go
- pkg/sip/inbound.go
- pkg/sip/outbound.go
- pkg/sip/room.go
- pkg/siptest/client.go
- test/lktest/livekit.go
Split audio and DTMF  RTP streams and accumulate timestamps independently. Update RTP timestamp properly when applying DTMF delay.
> Correctly set RTP timestamps when delaying DTMF

- pkg/media/rtp/conn.go
- pkg/siptest/client.go
- test/integration/sip_test.go
This helps disconnect problematic calls earlier (5 sec vs 30 sec).
> Reduce media timeout

- pkg/sip/signaling.go
- pkg/sip/signaling_test.go
Some softphones (Linphone) set codecs in SDP's media definition, but do not explicitly list it in the attributes. In this case SIP media currently fails. This change fixes this issue, improving our compatibility with these softphones.
> Consider codecs set in SDP formats, but not in attrs

- pkg/media/rtp/rtp.go
- pkg/sip/inbound.go
- pkg/sip/outbound.go
Seems like reusing the SSRC was spec-compliant after all. Provider tests were failing without it.
> Revert separate SSRC

- pkg/media/dtmf/dtmf.go
- pkg/media/dtmf/dtmf_test.go
- pkg/media/rtp/rtp.go
Improve compliance with DTMF RFC4733:
- Resend end event multiple times for reliability.
- Preserve event start timestamp in the update events.
> Better compliance with the DTMF RFC4733

- pkg/sip/outbound.go
room is not always set, just warn for now when it's empty and we're unable to set the participant attributes.
> nil room panic

- pkg/sip/inbound.go
The stack trace of the panic shows that this happens in the case where the SIP server never finishes the handshake. This means that the SDK never connects to the room, and LocalParticipant is nil when handling the connection time out
> Add nil check to prevent panic if room is not connected

- pkg/sip/client.go
- pkg/sip/inbound.go
- pkg/sip/outbound.go
- pkg/sip/room.go
- pkg/stats/monitor.go
A few small-ish fixes for the metrics:
- Simplify outbound code a bit.
- Make sure outbound call metric is decreased.
- Adjust duration buckets for short and long operations.
- Use from/to host instead of a full URI or the number for the metric.
> Improve metrics, make it safer

- go.mod
- go.sum
Update sipgo which includes a few back-ported commits from upstream. This fixes address parsing, allowing use of Linphone to accept outbound calls.
> Update sipgo. Fix address parsing.

- pkg/sip/inbound.go
- pkg/sip/media_port.go
- pkg/sip/outbound.go
Do not log errors triggered by bad user configuration, or connectivity issue with a SIP endpoint as Error.
> Adjust some spammy log levels

- pkg/media/rtp/conn.go
- pkg/service/psrpc.go
- pkg/service/service.go
- pkg/sip/client.go
- pkg/sip/inbound.go
- pkg/sip/media_port.go
- pkg/sip/outbound.go
- pkg/sip/protocol.go
- pkg/sip/room.go
- pkg/sip/server.go
- pkg/sip/service_test.go
- pkg/sip/types.go
- pkg/siptest/client.go
- test/integration/sip_test.go
- test/lktest/livekit.go
Refactor SIP signaling an change the call flow for both inbound and outbound.
For inbound **with PIN** (almost the same as before):
- Keep sending Ringing status for the whole time until the call is accepted.
- Signal to SIP peer as soon as we can and run the audio for the pin prompts.
- Given the PIN, join selected room on LK server.
- Immediate publish SIP track and subscribe to the rest.
For inbound **without PIN**:
- Keep sending Ringing status for the whole time until the call is accepted.
- First connect to the LK room according to dispatch rules.
- Subscribe and wait for at least one audio track. This is important! SIP now **keeps ringing** until there's one other participant with enabled audio track.
- Accept the call on SIP side. Wait for the first media packet.
- Publish SIP …
> Change the call flow. Defer track subscription.

- pkg/sip/inbound.go
- pkg/sip/outbound.go
- pkg/sip/protocol.go
Some SIP peers hang up immediately while some expect us to hang up first
> When a Refer succeeds, give time for the peer to hang up first, but hang up ourselves if this doesn't happen within 1 second

- pkg/config/config.go
- pkg/sip/client.go
- pkg/sip/config.go
- pkg/sip/inbound.go
- pkg/sip/media_port.go
- pkg/sip/media_port_test.go
- pkg/sip/outbound.go
- pkg/sip/server.go
- pkg/sip/signaling.go
- pkg/sip/types.go
- pkg/siptest/client.go
- test/integration/sip_test.go
Always set contact header for outbound to IP address instead of the hostname. Also, refactor the code to use `netip.Addr` and `netip.AddrPort`.
> Always set contact header for outbound to IP.

- go.mod
- go.sum
- pkg/sip/room.go
Getting the roomID in the callback logs required the used of an extra utilities because the room SID is only available after join, while some callbacks may fire before Join returns. room.SID() also takes the room lock which is already held in the participant callbacks. This means that we can't call room.SID() in the participant callbacks.
> Log more information in room callbacks

- .github/workflows/docker.yaml
To resolve warnings in workflow executions e.g. https://github.com/livekit/sip/actions/runs/12571680629/job/35042840405#step:9:8
> Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Reference https://github.com/docker/login-action/releases
> Bump docker/login-action to v3

- docker-compose.yaml
This MR makes the following updates to the `docker-compose.yml` file:  
1. **Redis Port Configuration:**
- Removed the deprecated  `expose` directive for Redis and changed for `ports` directive.
2. **Livekit Server Improvements:**
- Added a `depends_on` directive for the `livekit` service to ensure it starts only after the `redis` service is up and running.  
- Introduced a `condition: service_started` to improve service reliability during startup.
These changes enhance service dependencies and improve Redis accessibility, especially for local development and testing environments.
Tested with Docker version 27.4.1
> Update Redis Configuration and Add Dependency Management in docker-compose.yml

- README.md
Current hyperlink https://docs.livekit.io/sip/quickstart/ here redirects to Agents quickstarts, proposing updating to the SIP quickstarts page
> Correct SIP Quickstart hyperlink in README.md

- README.md
Should mention the media ports 10000-20000 instead of 1000-2000 similar to rest of the docs: https://docs.livekit.io/home/self-hosting/sip-server/
> Tiny typo in readme

- pkg/sip/room.go
If the room is closed quickly after connect, we could end up with a nil `r.room`.
> fix: prevent log resolver panic

- .github/workflows/build.yaml
No cache is being saved here currently, below messages are logged in workflow executions e.g. https://github.com/livekit/sip/actions/runs/13057592439/job/36432439669#step:3:14
> Cache not found for input keys: sip
and https://github.com/livekit/sip/actions/runs/13057592439/job/36432439669#step:7:2
> Warning: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
As such, the usage of actions/cache here is not really doing anything - proposing removing.
Modifying the usage of actions/cache a bit following https://github.com/actions/cache/blob/main/examples.md#go---modules does not resolve these messages, the workflow would need to additionally - or instead - utilize https://github.com/actions/setup-go?tab=readme-ov-file#caching-de …
> Remove actions/cache usage in workflows/build.yaml

- pkg/stats/monitor.go
This will help:
- identify throttling of the go process
- autoscale based on the amount of available pods
> Register go process metrics. Register node availability metric

- .github/workflows/test.yaml
- go.mod
- go.sum
- pkg/media/resample_soxr.go
- pkg/media/resample_test.go
- pkg/sip/media_port_test.go
Fix memory leak in resampler. While at it, optimize it for (almost) zero copy.
SIP now includes bindings for Soxr resampler instead of using a third-party library. Leak is _not_ caused by the library, to be clear.
Binding directly to Soxr makes it easier to use automatic cleanup function and avoid copying and reformatting the data, which also reduces GC pressure and CPU cycles.
This change also adds a test to avoid resampler memory leaks in the future.
> Fix memory leak in resampler

- .gitignore
- pkg/media/rtp/jitter.go
- pkg/siptest/client.go
- test/cloud/cloud.go
- test/cloud/config.go
- test/cloud/integration_test.go
- test/cloud/io.go
- test/cloud/phone.go
- test/cloud/service.go
packet pointer is reused by the connection, jitter buffer fills with copies of the pointer and never recovers from the sequence number skip caused by dtmf
> fix jitter buffer

- go.mod
- go.sum
- pkg/media/dtmf/dtmf.go
- pkg/media/rtp/conn.go
- pkg/media/rtp/jitter.go
- pkg/media/rtp/listen.go
- pkg/media/rtp/mux.go
- pkg/media/rtp/rtp.go
- pkg/media/rtp/session.go
- pkg/media/sdp/offer.go
- pkg/media/sdp/offer_test.go
- pkg/media/srtp/srtp.go
- pkg/service/psrpc.go
- pkg/sip/client.go
- pkg/sip/inbound.go
- pkg/sip/media.go
- pkg/sip/media_port.go
- pkg/sip/media_port_test.go
- pkg/sip/outbound.go
- pkg/sip/participant.go
- pkg/sip/protocol.go
- pkg/sip/server.go
- pkg/sip/service_test.go
- pkg/sip/types.go
- pkg/siptest/client.go
Supporting protocol PR:
- https://github.com/livekit/protocol/pull/892
> Support SRTP

- pkg/sip/config.go
This makes code consistent with other services.
> Use TURN to establish external IP

- pkg/media/sdp/helpers.go
- pkg/media/sdp/helpers_test.go
- pkg/media/sdp/offer.go
- pkg/media/sdp/offer_test.go
👋🏼  This patch addresses an issue in the media SDP parsing logic where session-level connection information (c=) was always used, even if a media-level c= was present. As I understand it media sections may override the session-level connection address; and if absent, they should inherit it.
Changes
- pkg/media/sdp/helpers.go
- Updated GetAudioDest to first check audio.ConnectionInformation (media-level), then fall back to session.ConnectionInformation.
- Preserves existing validity checks on ci.NetworkType and handles nil cases gracefully.
- pkg/media/sdp/offer.go
- Existing logic now errors on invalid addresses instead of passing it along w/o errors.
- Downstream components relying on correct RTP addresses should no longer see spurious “invalid AddrPort” errors when media-level c= is …
> Support media-level c= fallback to session-level connection in SDP parsing

- pkg/sip/inbound.go
- pkg/sip/server.go
**Summary**
This change implements handling of the SIP OPTIONS method in the server. The server now responds with a 200 OK to inbound OPTIONS requests.
**Motivation**
Some SIP trunk providers — such as CM.com — require a valid response to periodic OPTIONS requests before they will route calls to a SIP destination. These requests function as a form of connection heartbeat, confirming the availability of the SIP endpoint. Without this (small) change, the SIP server cannot be used with certain SIP trunk providers.
**Implementation Details**
Added support for the OPTIONS method.
The server responds with 200 OK to any valid inbound OPTIONS request.
> Respond to SIP OPTIONS requests with 200 OK to support trunk provider heartbeat and connection validation

- pkg/internal/ringbuf/buffer.go
- pkg/mixer/mixer.go
When determining the amount of times to run the mixer, use the media end time enqueued during the previous run, instead of the wall clock time of the end of the last run. If the ticker runs late, or the mixing takes a non negligible amount of time, we would currently ignore partial frame times, potentially causing us to enqueue too little media.
> Track mixer target output time between runs

- pkg/sip/inbound.go
When a CANCEL is received for an INVITE that hasn't been answered, the SIP gateway now correctly sends a 487 response to the original INVITE. This ensures proper SIP transaction termination and avoids issues where upstream proxies (e.g., Brekeke) keep the call in an INVITE state due to the missing final response.
closes #371
> fix(sip): send 487 Request Terminated after OK (CANCEL) for pending INVITE

- pkg/sip/inbound.go
- pkg/sip/server.go
This could make it easy to search logs when we have attributes like the call id but we haven't handled the sip request
> Detailed log for unhandled sip requests

- pkg/sip/service.go
- pkg/sip/tls.go
In SIP, each call leg may have a different transport, including TLS. And the leg of the call is usually identified with an IP instead of the hostname, which breaks default TLS cert verification. This change removes the check for the hostname, while still verifying the cert chain against root CAs.
> Validate only TLS cert validity, not the hostname.
